### ISSUE TITLE
When using fetchTicker, returns Optional(8200)

### ISSUE THREAD

**Issue by aaronr22** [iCell/CryptoCurrencyKit#1]

**Comment by iCell** [comment]
Could you send me a screenshot? I’ll fix the issue once I find out where the bug is. Thank you for your feedback.

2017年11月26日 +0800 AM8:10 aaronr22 <notifications@github.com>，写道：

**Comment by aaronr22** [comment]
I have the same issue again. It is something I am doing wrong but I cannot figure it out.  Thanks.
```
func getJSON() {
        Alamofire.request("https://api.coinmarketcap.com/v1/ticker/ethereum/", encoding: JSONEncoding.default)
            .responseJSON { response in
                //to get JSON return value
                if let result = response.result.value {
                     let JSON = result as! [[String:Any]]
                    print(JSON[0]["price_usd"])
                    let price = JSON[0]["price_usd"]
```

**Comment by iCell** [comment]
The "price_usd" field may be empty in some return values, so it must be marked as Optional.
